### PR TITLE
Add PNG export functionality for flow charts

### PR DESCRIPTION
**Pull request by IlIIIIIIlI**
Hi AbianS! 👋

I've added a "Download" button for this awesome flow charts! 🎉

What's cool about it:
✨ Sits nicely in the top-left corner
🖼️ Captures the whole flow chart (horizontal or vertical)
🔍 Creates high-res images (4x scaling) with a transparent background
🎯 Smartly excludes UI stuff like minimap and controls
⏳ Shows a cute loading spinner while working its magic

Tech stuff:
🛠️ Used html-to-image for the capture (it's pretty neat!)
🧩 Made it a separate component so we can easily add more formats later (PDF, SVG, etc.)

I had fun working on this! Let me know what you think or if you want me to change anything. 😊

### CODE REVIEW

**Comment by AbianS** [comment]
Hi! 👋

First of all, I think this is a fantastic idea, and I love how you've implemented it! The download button and all the features you’ve added are super useful, and I appreciate the attention to detail, like excluding UI elements and providing high-res images. 🎉

The only thing I noticed is that when downloading the PNG, there's a small shift in the diagram before it snaps back to its original position. I’ve just pushed a few corrections that should improve this, and I'd love to hear your thoughts on them. If you agree and like the changes, we can go ahead and merge it! 😊

Thanks again for your awesome work!

**Comment by AbianS** [comment]
I’ve updated the download component to a download button located in the controls instead of text.

Here’s an image for reference:

image

What do you think? 😊

**Comment by IlIIIIIIlI** [comment]
Thanks for perfectly correcting the issue, AbianS! Your fix is spot-on and greatly improves the feature. Really appreciate your attention to detail.

This design is great!

**Comment by AbianS** [comment]
Thanks! I'm glad you liked the fix! 😊

So, do you think it's ready to merge? Let me know if everything looks good to you.

**Comment by AbianS** [comment]
My idea for the future is to add a side menu that will contain multiple configuration options, including different export formats. This way, we can keep the interface clean while offering more flexibility.

**Comment by IlIIIIIIlI** [comment]
That's a good idea. Besides that, I'm very satisfied with the current changes. I really admire how you've further refined the code structure. The more granular component breakdown and clearer organization make the codebase much more maintainable and easier to understand. Great job on improving the overall architecture!

**Comment by AbianS** [comment]
This is the menu: [Leva](https://www.npmjs.com/package/leva). If needed, I might implement a custom one, but it'll function similarly.

**Pull request merged**
